### ISSUE TITLE
Issues with Reactor 

### ISSUE THREAD

**Issue by woksin** [Cratis/Chronicle#1411]
The code of the reactor on method is completed but it starts a failing partition and keeps failing

Timeout
An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at Cratis.Chronicle.Services.Observation.Reactors.Reactors.<>c__DisplayClass3_0.<Observe>b__3(IEnumerable`1 events, TaskCompletionSource`1 tcs)
   at Cratis.Chronicle.Grains.Observation.Reactors.Clients.ReactorMediator.OnNext(ReactorId reactorId, ConnectionId connectionId, IEnumerable`1 events, TaskCompletionSource`1 taskCompletionSource)
   at Cratis.Chronicle.Grains.Observation.Reactors.Clients.ReactorObserverSubscriber.OnNext(IEnumerable`1 events, ObserverSubscriberContext context)
   at Orleans.Runtime.TaskRequest`1.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 686
--- End of stack trace from previous location ---
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 132
   at Cratis.Chronicle.Orleans.Transactions.UnitOfWorkIncomingCallFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 94
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IGrainContext target, Message message) in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 267
   at Orleans.Serialization.Invocation.ResponseCompletionSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 81
   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 117
   at Cratis.Chronicle.Orleans.Transactions.UnitOfWorkOutgoingCallFilter.Invoke(IOutgoingGrainCallContext context)
   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 88
   at Orleans.Runtime.GrainReferenceRuntime.InvokeMethodWithFiltersAsync[TResult](GrainReference reference, IInvokable request, InvokeMethodOptions options) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 90
   at Cratis.Chronicle.Grains.Observation.Jobs.HandleEventsForPartition.PerformStep(HandleEventsForPartitionArguments request, CancellationToken cancellationToken)
   
An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at Cratis.Chronicle.Services.Observation.Reactors.Reactors.<>c__DisplayClass3_0.<Observe>b__3(IEnumerable`1 events, TaskCompletionSource`1 tcs)
   at Cratis.Chronicle.Grains.Observation.Reactors.Clients.ReactorMediator.OnNext(ReactorId reactorId, ConnectionId connectionId, IEnumerable`1 events, TaskCompletionSource`1 taskCompletionSource)
   at Cratis.Chronicle.Grains.Observation.Reactors.Clients.ReactorObserverSubscriber.OnNext(IEnumerable`1 events, ObserverSubscriberContext context)
   at Orleans.Runtime.TaskRequest`1.Invoke() in /_/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs:line 686
--- End of stack trace from previous location ---
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 132
   at Cratis.Chronicle.Orleans.Transactions.UnitOfWorkIncomingCallFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Core/Core/GrainMethodInvoker.cs:line 94
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IGrainContext target, Message message) in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 267
   at Orleans.Serialization.Invocation.ResponseCompletionSource.GetResult(Int16 token) in /_/src/Orleans.Serialization/Invocation/ResponseCompletionSource.cs:line 81
   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 117
   at Cratis.Chronicle.Orleans.Transactions.UnitOfWorkOutgoingCallFilter.Invoke(IOutgoingGrainCallContext context)
   at Orleans.Runtime.OutgoingCallInvoker`1.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 88
   at Orleans.Runtime.GrainReferenceRuntime.InvokeMethodWithFiltersAsync[TResult](GrainReference reference, IInvokable request, InvokeMethodOptions options) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 90
   at Cratis.Chronicle.Grains.Observation.Jobs.HandleEventsForPartition.PerformStep(HandleEventsForPartitionArguments request, CancellationToken cancellationToken)
C

**Comment by woksin** [comment]
This was related to this issue https://github.com/Cratis/Chronicle/issues/1324

**Comment by woksin** [comment]
Fixed by #1412, but we should find a more sophisticated solution. Look at #1324
